name: JK test
favicon: null
layout_spectrum: 0.0071
typography_spectrum: 0.24139
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff6'
    - '#272c30'
    - '#c3c1b4'
    - '#454648'
    - '#676556'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
